displayName=Maze Race Bingo
internalName=maze-race-bingo
description=Automatically tracks task progress for Maze Race Bingo
tags=maze,race,bingo,tracker,task
author=Clerqy
plugins=com.mazebingo.MazeBingoPlugin
version=
build=standard